### Cadastrar Lista de funcionários
POST http://localhost:5291/api/funcionario/cadastrar/lista
Content-Type: application/json

[
  {
    "Nome": "Ana Maria Silva",
    "DataNascimento": "1985-03-12T00:00:00",
    "CPF": "12345678901",
    "Sexo": "F",
    "Cargo": "Diretor(a) do Presídio",
    "Senha": "senha123"
  },
  {
    "Nome": "Carlos Eduardo Oliveira",
    "DataNascimento": "1990-07-25T00:00:00",
    "CPF": "23456789012",
    "Sexo": "M",
    "Cargo": "Agente de Segurança Penitenciária (ASP)",
    "Senha": "senha456"
  },
  {
    "Nome": "Juliana Pereira",
    "DataNascimento": "1992-05-10T00:00:00",
    "CPF": "34567890123",
    "Sexo": "F",
    "Cargo": "Assistente Social",
    "Senha": "senha789"
  },
  {
    "Nome": "Marcelo Fernandes",
    "DataNascimento": "1988-01-18T00:00:00",
    "CPF": "45678901234",
    "Sexo": "M",
    "Cargo": "Chefe de Vigilância e Disciplina",
    "Senha": "senha1234"
  },
  {
    "Nome": "Beatriz Souza",
    "DataNascimento": "1995-09-14T00:00:00",
    "CPF": "56789012345",
    "Sexo": "F",
    "Cargo": "Enfermeiro(a) Penitenciário(a)",
    "Senha": "senha5678"
  },
  {
    "Nome": "Rafael dos Santos",
    "DataNascimento": "1983-06-30T00:00:00",
    "CPF": "67890123456",
    "Sexo": "M",
    "Cargo": "Agente Penitenciário Especializado",
    "Senha": "senha9012"
  },
  {
    "Nome": "Paula Azevedo",
    "DataNascimento": "1978-12-01T00:00:00",
    "CPF": "78901234567",
    "Sexo": "F",
    "Cargo": "Nutricionista",
    "Senha": "senha3456"
  },
  {
    "Nome": "Lucas Moura",
    "DataNascimento": "1998-04-15T00:00:00",
    "CPF": "89012345678",
    "Sexo": "M",
    "Cargo": "Professor(a) de Educação Prisional",
    "Senha": "senha6789"
  },
  {
    "Nome": "Fernanda Ribeiro",
    "DataNascimento": "1987-11-22T00:00:00",
    "CPF": "90123456789",
    "Sexo": "F",
    "Cargo": "Coordenador(a) de Educação e Trabalho",
    "Senha": "senha2345"
  },
  {
    "Nome": "João Vitor Almeida",
    "DataNascimento": "1993-03-08T00:00:00",
    "CPF": "01234567890",
    "Sexo": "M",
    "Cargo": "Médico(a) Penitenciário(a)",
    "Senha": "senha9876"
  }
]
