### Cadastrar Lista de detentos
POST http://localhost:5291/api/detento/cadastrar/lista
Content-Type: application/json

[
    {
        "Nome": "João da Silva",
        "DataNascimento": "1980-05-12",
        "CPF": "123.456.789-00",
        "Sexo": "M",
        "InicioPena": "2022-01-15T00:00:00",
        "FimPena": "2032-01-15T00:00:00"
    },
    {
        "Nome": "Maria Oliveira",
        "DataNascimento": "1992-08-23",
        "CPF": "987.654.321-00",
        "Sexo": "F",
        "InicioPena": "2021-06-10T00:00:00",
        "FimPena": "2031-06-10T00:00:00"
    },
    {
        "Nome": "Carlos Pereira",
        "DataNascimento": "1975-11-30",
        "CPF": "456.789.123-00",
        "Sexo": "M",
        "InicioPena": "2023-03-25T00:00:00",
        "FimPena": "2035-03-25T00:00:00"
    },
    {
        "Nome": "Ana Costa",
        "DataNascimento": "1985-07-19",
        "CPF": "654.321.987-00",
        "Sexo": "F",
        "InicioPena": "2020-11-05T00:00:00",
        "FimPena": "2028-11-05T00:00:00"
    },
    {
        "Nome": "Roberto Souza",
        "DataNascimento": "1978-01-09",
        "CPF": "321.654.987-00",
        "Sexo": "M",
        "InicioPena": "2018-04-10T00:00:00",
        "FimPena": "2028-04-10T00:00:00"
    },
    {
        "Nome": "Paula Mendes",
        "DataNascimento": "1995-02-17",
        "CPF": "789.123.456-00",
        "Sexo": "F",
        "InicioPena": "2023-09-01T00:00:00",
        "FimPena": "2029-09-01T00:00:00"
    },
    {
        "Nome": "Fernando Rocha",
        "DataNascimento": "1983-10-30",
        "CPF": "963.852.741-00",
        "Sexo": "M",
        "InicioPena": "2022-06-15T00:00:00",
        "FimPena": "2030-06-15T00:00:00"
    },
    {
        "Nome": "Luiza Fernandes",
        "DataNascimento": "1990-09-24",
        "CPF": "852.963.741-00",
        "Sexo": "F",
        "InicioPena": "2021-08-20T00:00:00",
        "FimPena": "2031-08-20T00:00:00"
    },
    {
        "Nome": "Diego Moreira",
        "DataNascimento": "1987-12-05",
        "CPF": "741.852.963-00",
        "Sexo": "M",
        "InicioPena": "2023-01-18T00:00:00",
        "FimPena": "2033-01-18T00:00:00"
    },
    {
        "Nome": "Clara Azevedo",
        "DataNascimento": "1998-03-14",
        "CPF": "159.753.486-00",
        "Sexo": "F",
        "InicioPena": "2024-02-10T00:00:00",
        "FimPena": "2032-02-10T00:00:00"
    }
]
