@base_url = http://localhost:5291/api/detento
@detentoId = 332788f7-92d9-4faa-9e6c-3fa402b955df

### Cadastrar Detento
POST {{base_url}}/cadastrar
Content-Type: application/json

{
    "Nome" : "Leonardo",
    "DataNascimento" : "12/10/2000",
    "CPF" : "61725312434",
    "Sexo" : "M",
    "TempoPenaInicial" : 1478, 
    "PenaRestante" : 1478,
    "InicioPena" : "13/10/2024",
    "FimPena" : "13/10/2039"
}

### Buscar Detento
GET {{base_url}}/buscar/{{detentoId}}

### Alterar Detento
PUT {{base_url}}/alterar/{{detentoId}}
Content-Type: application/json

{
    "Nome" : "Joelson Menedes da Silva",
    "DataNascimento" : "25/12/1970",
    "CPF" : "72761910524",
    "Sexo" : "M",
    "TempoPenaInicial" : 500, 
    "PenaRestante" : 200,
    "InicioPena" : "10/02/2024",
    "FimPena" : "09/05/2029"
}
### Deletar detento
DELETE {{base_url}}/deletar/{{detentoId}}