@base_url = http://localhost:5291/api/atividade
@DetentoId = 
@AtividadeId = 
@nomeAtividade = todos

### Criar Atividades e adicionar a Detento
POST {{base_url}}/detento/cadastrar/{{DetentoId}}/{{nomeAtividade}}

### Listar atividades de Um detento
GET {{base_url}}/listar/detento/{{DetentoId}}

### Alterar atividade [rascunho lógica de redução de pena]
PUT {{base_url}}/alterar/{{AtividadeId}}
Content-Type: application/json

{
  "Limite" : 14
}

### Adicionar atividades em todos os detentos [facilitar testes]
POST {{base_url}}/detento/cadastrar/todas

### Arrumar atividade
PUT http://localhost:5291/api/arrumarTiposAtividade