@base_url = http://localhost:5291/api/atividade
@DetentoId = ad16bda7-5f39-4d69-ad9a-b0d0a77894f1
@AtividadeId = dfd5902f-8417-4ea2-b2d6-46fa1ff6ec70
@nomeAtividade = todos
### Criar Atividades e adicionar a Detento
POST {{base_url}}/detento/cadastrar/{{DetentoId}}/{{nomeAtividade}}

### Listar atividades de Um detento
GET {{base_url}}/listar/detento/{{DetentoId}}

### Alterar atividade [rascunho lógica de redução de pena]
PUT {{base_url}}/alterar/{{AtividadeId}}
Content-Type: application/json

{
  "Limite" : 14
}