@base_url = http://localhost:5291/api/detento
@detentoId = cb581b16-3831-40fc-89b2-13d0b52ba063
@atividades = todas

### Cadastrar Detento
POST {{base_url}}/cadastrar
Content-Type: application/json

{
    "Nome": "Vinícius Martins",
    "DataNascimento": "1982-04-28",
    "CPF": "753.159.486-00",
    "Sexo": "M",
    "InicioPena": "2025-07-15T00:00:00",
    "FimPena": "2035-07-15T00:00:00"
}

### Buscar Detento
GET {{base_url}}/buscar/id:{{detentoId}}

### Buscar Detento por CPF
GET {{base_url}}/buscar/cpf:753.159.486-00

### Alterar Detento
PUT {{base_url}}/alterar/{{detentoId}}
Content-Type: application/json

{
    "Nome": "Choi Beomgyu",
    "DataNascimento": "1982-04-28",
    "CPF": "753.159.486-00",
    "Sexo": "M",
    "InicioPena": "2025-07-15T00:00:00",
    "FimPena": "2035-07-15T00:00:00"
}

### Listar Detentos
GET http://localhost:5291/api/detento/listar

### Deletar detento
DELETE {{base_url}}/deletar/{{detentoId}}