// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241008011537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("API.Models.Atividade", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnoAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Contador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetentoId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Equivalencia")
                        .HasColumnType("REAL");

                    b.Property<string>("Limite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetentoId");

                    b.ToTable("TabelaAtividade");
                });

            modelBuilder.Entity("API.Models.Pessoa", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelaPessoa");

                    b.HasDiscriminator().HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("API.Models.Detento", b =>
                {
                    b.HasBaseType("API.Models.Pessoa");

                    b.Property<DateTime>("FimPena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioPena")
                        .HasColumnType("TEXT");

                    b.Property<int>("PenaRestante")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoPenaInicial")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Detento");
                });

            modelBuilder.Entity("API.Models.Atividade", b =>
                {
                    b.HasOne("API.Models.Detento", null)
                        .WithMany("ListaAtividades")
                        .HasForeignKey("DetentoId");
                });

            modelBuilder.Entity("API.Models.Detento", b =>
                {
                    b.Navigation("ListaAtividades");
                });
#pragma warning restore 612, 618
        }
    }
}
