// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20241113171225_TabelaInativo")]
    partial class TabelaInativo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("API.Models.Atividade", b =>
                {
                    b.Property<string>("AtividadeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AnoAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Contador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetentoId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetentoInativoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<double>("Equivalencia")
                        .HasColumnType("REAL");

                    b.Property<int>("Limite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AtividadeId");

                    b.HasIndex("DetentoId");

                    b.HasIndex("DetentoInativoId");

                    b.ToTable("TabelaAtividades");

                    b.HasDiscriminator().HasValue("Atividade");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("API.Models.Detento", b =>
                {
                    b.Property<string>("DetentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FimPena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioPena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("DetentoId");

                    b.ToTable("TabelaDetentos");
                });

            modelBuilder.Entity("API.Models.DetentoInativo", b =>
                {
                    b.Property<string>("DetentoInativoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FimPena")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioPena")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("DetentoInativoId");

                    b.ToTable("TabelaDetentosInativos");
                });

            modelBuilder.Entity("API.Models.Funcionario", b =>
                {
                    b.Property<string>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .HasColumnType("TEXT");

                    b.Property<char>("Sexo")
                        .HasColumnType("TEXT");

                    b.HasKey("FuncionarioId");

                    b.ToTable("TabelaFuncionarios");
                });

            modelBuilder.Entity("API.Models.Estudo", b =>
                {
                    b.HasBaseType("API.Models.Atividade");

                    b.HasDiscriminator().HasValue("Estudo");
                });

            modelBuilder.Entity("API.Models.Leitura", b =>
                {
                    b.HasBaseType("API.Models.Atividade");

                    b.HasDiscriminator().HasValue("Leitura");
                });

            modelBuilder.Entity("API.Models.Trabalho", b =>
                {
                    b.HasBaseType("API.Models.Atividade");

                    b.HasDiscriminator().HasValue("Trabalho");
                });

            modelBuilder.Entity("API.Models.Atividade", b =>
                {
                    b.HasOne("API.Models.Detento", null)
                        .WithMany("Atividades")
                        .HasForeignKey("DetentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.DetentoInativo", null)
                        .WithMany("Atividades")
                        .HasForeignKey("DetentoInativoId");
                });

            modelBuilder.Entity("API.Models.Detento", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("API.Models.DetentoInativo", b =>
                {
                    b.Navigation("Atividades");
                });
#pragma warning restore 612, 618
        }
    }
}
